<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
    <title>Keep It Simple</title>
    <meta http-equiv="content-type" content="application/xhtml+xml; charset=UTF-8" />
    <link rel="stylesheet" type="text/css" media="screen" href="css/blog/screen.css" />
</head>
<body>
<div id="header-wrap">
    <div id="header" class="container_16">
        <h1 id="logo-text"><a href="#">Keep It Simple</a></h1>
        <p id="intro">My Simple Blog, Powered by Laminas...</p>
        <div  id="nav">
            <ul>
                <li><a href="#">Blog</a></li>
                <li><a href="#">Admin</a></li>
            </ul>
        </div>
        <div id="header-image"></div>
    </div>
</div>
<div id="content-outer">
    <div id="content-wrapper" class="container_16">
        <div id="main" class="grid_12">
            <h2><a href="#">Post Title</a></h2>
            <p>Post Body</p>
            <p class="postmeta"><a href="#" class="comments">Comments (Number)</a> | <span class="date">Post Date</span> </p>
            <div class="clear">&nbsp;</div>
        </div>
        <div id="left-columns" class="grid_4">
            <div class="grid_4 omega">
                <h3>About Me</h3>
                <div class="featured-post">
                    <h4><a href="#">Vahid Vahedi</a></h4>
                    <p> <a href="#"><img src="img/blog/image.jpg" width="160" height="100" alt="" class="float-left" />
                        </a>Web Developer and PHP Lover. I enjoy developing large applications by setting and following best practices guidelines to have a homogeneous and well-tested codebase. Following technical standards and having team conventions, as well as giving motivations for a personal development style, is my favorite team working style.</p>
                </div>
            </div>
        </div>
    </div>
</div>
<div id="footer-wrapper" class="container_16">
    <div id="footer-bottom">
        <p class="bottom-left"> &nbsp; &copy;2022 All rights reserved. &nbsp; &nbsp; Design by : Vahid Vahedi </p>
        <p class="bottom-right" > <a href="#">Blog</a> | <a href="#">Admin</a> </p>
    </div>
</div>
</html>
